modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/CerealCamera/Aviator-Dreams-Reloaded/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "aviator_dream"
version = "${version}"
displayName = "Aviator Dreams"
displayURL = ""
authors = "CerealCamera"
description = "An Add-On aimed at adding real life airliners to the game."
logoFile = "icon.png"
itemIcon = "aviator_dream:douglas_dc1"

[[dependencies.aviator_dream]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT_VERSION@,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aviator_dream]]
modId = "immersive_aircraft"
mandatory = true
versionRange = "[1.2.2,)"
ordering = "NONE"
side = "BOTH"
